language: node_js
sudo: false
addons:
  apt:
    packages:
    - lftp
os: linux
node_js:
  - "10"
branches:
  only:
  - master
env:
  global:
    - secure: "GC/Cg7n22aKeSyBN5BnUWmoWpxFXRVLGBdrg9+U9wHlYr9RfwAujaJPUM7qLPSXf3cMuKDRRysHtSY6Qaje1St048PX/nZx7tgOVnrpAUCnyDv1/xXURtHBzL8T4pFsPeiGGJKfIq3tuP5SNKMQmxRRxzA1Y6hkw9WsnaO30q9D
      2Cqh1vfzt05u9QdMgu8N/dqMc8BsZzReVNwNg1mXGJeIO9pDMM+VJoMkfKDnWq0xcvEztnsxFuggQ4Giw4gdELXu4uDH0j27LmB69uctSElhfe0avtJigwFQpXywqRs70Dy1rdCgiSZ+P3yQCXdHbwHfAl6c++aOj5MG4F2CpY311MOxM9UUMD
      NwTHkG6ay2lxl2HHNWy4sVHG2pxyeNacv7/nSSk6JFrC3SxItuf+WapQaALjqi+UXlW4XO0iXY5LfL18Q7kKwY8DafhmQUMXFBT8fYwKF4DOo7gCEfrI1MPcMai0+tQKuzozHuSLilMtRvG4hujO2hfY3VnHDxN5m9U4vaZY5zxKlmqYyus4hN
      /YrcNd/l4L4I56PgEG0ZNqlQZBf40cxaiS4ZSWJ2dIeh9wXFYQHPcStXUmRtrbtp6OHwmGoBNwv8renzG2JihZdtl43ATfGicedwvtdCW1t+g1IyxMVavXZI6jpKt4CAVvlxkuk0QEbQNRVr/2gQ="
    - secure: "s6ZktWUqfOSx4bdnFWgawKPKGpkF91n0Al1Joj0fd61h3EgS8/Tg7dfTbjvBPuFOHMTIhruYN3oNxubh5h4tkAPoOzPdNPPAtwFk6Bq/zdVTrTp4M6AOin7XvD6WLxbsT2AS5tOCVkewptDPejVTk98Z0IQzz0kUabBbOwUNLzP
      fM4C+85lB9Jv2FBMFY0koij1Nt9/814j1pfaHgwJIdvSoHl7Zpid68LA9nQZHk109zX+lOZl8ngmEGS8poe1/X0uw3C8VEAUdzIUAtAn/6sTCp0Ynm+cjyCWBfpYl62wIFk1RR7u+zeQb6ZfngrMlK5TKob4cw8GKfbXFqmS1pbZyss1nxv2fi
      uNQLYx5/hUcx/mN8h0sVE4rgkSqYh0GVa1pWZTTBURfI7MPuLxOxl9MyzMbZ+jMhEBYOno/hf4wWm38QxEnvqFn71aOEMJi9uuLioFalBD2tncomWEg/Jk2DEU8RrSSGXAf6EGSFvNPMueJ9ULcemEuscoFckoK/7CRN/zIPfJxkv3+ZwyN6k7
      N0OkFKUWPvhf4DLgGNCQ+0l7OCnUgeeynnodfkr1bzg+DTksy2nm0Qv7u9oHQDrNV/UxWaOv+2gHyIFSRCC2VwpRlf7MO3IcpGu66kcwls8rqCZxhLGLYkWc0Ns3zDh/urY2i0YeKOKvQed1rIjA="
    - FTP_ADDRESS=ftp://s45.linuxpl.com/
install:
  - npm install
cache:
  bundler: true
  directories:
  - node_modules/
jobs:
  include:
#  - stage: Js lint
#    script: npm run lint
#  - stage: Test
#    script: npm run test
  - stage: Deploy
    script: bin/travis-deploy.sh

notifications:
  email:
  - kontakt@lukaszbanas.com.pl